// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Devise__PasswordStrengthController from "./devise/password_strength_controller"
application.register("devise--password-strength", Devise__PasswordStrengthController)

import Devise__WebauthnController from "./devise/webauthn_controller"
application.register("devise--webauthn", Devise__WebauthnController)

import Utilities__CopyCodeController from "./utilities/copy_code_controller"
application.register("utilities--copy-code", Utilities__CopyCodeController)

import Utilities__RemoteModalController from "./utilities/remote_modal_controller"
application.register("utilities--remote-modal", Utilities__RemoteModalController)