# Sample credentials file for XIVAuth. This file is not necessary for core development work and is here for reference.
# Use `rails credentials:edit --environment=development` to generate a dev version of this file for local use. Do not
# commit the encrypted file. Features that depend on but do not have a declared credential should simply be disabled
# silently.

oauth:
  discord:
    # See https://discord.com/developers/docs/topics/oauth2 for information on getting Discord credentials.
    client_id: DISCORD_CLIENT_ID
    client_secret: DISCORD_CLIENT_SECRET
  github:
    # See https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/creating-an-oauth-app for information on
    # getting GitHub Apps credentials. No Apps functionality is actually necessary.
    client_id: GITHUB_CLIENT_ID
    client_secret: GITHUB_CLIENT_SECRET
  steam:
    # See https://steamcommunity.com/dev for information on getting a Steam token. Domain does not seem to matter.
    token: STEAM_TOKEN
  twitch:
    # See https://dev.twitch.tv/docs/authentication/register-app/ for information on getting Twitch credentials.
    client_id: TWITCH_CLIENT_ID
    client_secret: TWITCH_CLIENT_SECRET
  patreon:
    # See https://www.patreon.com/portal/start/oauth-explained for information on getting Patreon credentials.
    client_id: PATREON_CLIENT_ID
    client_secret: PATREON_CLIENT_SECRET

postmark:
  # Create and use your own Postmark account. This shouldn't be necessary for local XIVAuth development.
  api_token: POSTMARK_API_TOKEN

active_record_encryption:
  # Generate these values with `rails db:encryption:init`. Hardcoded defaults are provided in development.rb for
  # developer quick starts.
  primary_key: AR_PRIMARY_KEY
  deterministic_key: AR_DETERMINISTIC_KEY
  key_derivation_salt: AR_KEY_DERIVATION_SALT