# Sample credentials file for XIVAuth. This file is not necessary for core development work and is here for reference.
# Use `rails credentials:edit --environment=development` to generate a dev version of this file for local use. Do not
# commit the encrypted file. Features that depend on but do not have a declared credential should simply be disabled
# silently.

oauth:
  discord:
    client_id: DISCORD_CLIENT_ID
    client_secret: DISCORD_CLIENT_SECRET
  github:
    client_id: GITHUB_CLIENT_ID
    client_secret: GITHUB_CLIENT_SECRET
  steam:
    token: STEAM_TOKEN
  twitch:
    client_id: TWITCH_CLIENT_ID
    client_secret: TWITCH_CLIENT_SECRET
  patreon:
    client_id: PATREON_CLIENT_ID
    client_secret: PATREON_CLIENT_SECRET

postmark:
  api_token: POSTMARK_API_TOKEN

active_record_encryption:
  # Generate these values with `rails db:encryption:init`.
  primary_key: AR_PRIMARY_KEY
  deterministic_key: AR_DETERMINISTIC_KEY
  key_derivation_salt: AR_KEY_DERIVATION_SALT