cleanup_unverified_characters:
  cron: 'every day at 2 am in America/Los_Angeles'
  class: 'CharacterRegistration::CleanupStaleRecordsJob'
  queue: 'cronjobs'

cleanup_stale_oauth:
  cron: 'every 6 hours'
  class: 'OAuth::CleanupStaleRecordsJob'
  queue: 'cronjobs'

cleanup_stale_users:
  cron: 'every day at 2 am in America/Los_Angeles'
  class: 'Users::CleanupUnconfirmedUsersJob'
  queue: 'cronjobs'

sync_webauthn_aaguids:
  cron: 'every thursday at 1 am in America/Los_Angeles'
  class: 'Webauthn::SyncAaguidsJob'
  queue: 'cronjobs'
