name: "Ruby on Rails CI"

on:
  workflow_call:

jobs:
  test:
    permissions:
      contents: read
      checks: write

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
      redis:
        image: redis:8-alpine
        ports:
          - "6379:6379"
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - uses: awalsh128/cache-apt-pkgs-action@v1.6.3
        with:
          packages: libvips

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      # Set up NodeJS and dependencies
      - uses: pnpm/action-setup@v6
        with:
          version: 11
      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'
      - name: Install JS dependencies
        run: pnpm install --frozen-lockfile

      - name: Precompile assets
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          bin/rails css:build || true
          bin/rails js:build || true
          bundle exec rails assets:precompile

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Run tests
        id: rspec
        run: bundle exec rspec --force-color --format documentation
        continue-on-error: true

      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tmp/testresults/rspec.xml
          report_type: test_results

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tmp/testresults/coverage/coverage.xml
          report_type: coverage

      - name: Report test results
        uses: mikepenz/action-junit-report@v6.5.0
        with:
          report_paths: 'tmp/testresults/rspec.xml'

  lint:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Generate binstubs
        run: bundle binstubs rubocop

      - name: Run rubocop with reviewdog
        uses: reviewdog/action-rubocop@v2.22.0
        with:
          reporter: github-pr-review
          only_changed: true
          skip_install: true
          use_bundler: true
